# Loadind the Dataset

In [4]:
import pandas as pd
df = pd.read_csv('C:\\Users\\SHRENI\\Desktop\\VIT\\3rd_sem\\Dataset\\IMDB Dataset.csv')

In [5]:
df.head(10)
df['review'][10]

'Phil the Alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines.<br /><br />At first it was very odd and pretty funny but as the movie progressed I didn\'t find the jokes or oddness funny anymore.<br /><br />Its a low budget film (thats never a problem in itself), there were some pretty interesting characters, but eventually I just lost interest.<br /><br />I imagine this film would appeal to a stoner who is currently partaking.<br /><br />For something similar but better try "Brother from another planet"'

# Transforming Documents into Feature Vectore

In [ ]:
# import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()

docs = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining, the weather is sweet, and one and one is two'])



In [8]:
bag=count.fit_transform(docs)
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [9]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


# Term Frequency and Inverse Document
#Term frequencies alone do not contribute to distinct information
#tf-idf (t,d) = tf(t,d) X idf(t,d)
#idf(t,d) = log(nd / 1 + df(d,t))
#where nd = total number of documents and df(d,t) = number of documents that contain the term t

In [15]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(use_idf = True, norm = 'l2', smooth_idf = True)

print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.         0.43370786 0.         0.55847784 0.55847784 0.
  0.43370786 0.         0.        ]
 [0.         0.43370786 0.         0.         0.         0.55847784
  0.43370786 0.         0.55847784]
 [0.50238645 0.44507629 0.50238645 0.19103892 0.19103892 0.19103892
  0.29671753 0.25119322 0.19103892]]


In [16]:
np.set_printoptions

<function numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, **kwarg)>

# Tokenization of Document

In [20]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()


def stemmer_tokenize(text):
    return [porter.stem(word) for word in text.split()]


stemmer_tokenize('coders like coding and thus they code')


['coder', 'like', 'code', 'and', 'thu', 'they', 'code']

# Vectorizing Documents

In [25]:
from sklearn.feature_extraction.text import  TfidfVectorizer
tfidf =  TfidfVectorizer(strip_accents = None, 
                        lowercase = False,
                       tokenizer = stemmer_tokenize,
                       use_idf = True,
                       norm = 'l2',
                       smooth_idf = True)

 

Y = df.sentiment.values
x = tfidf.fit_transform(df.review)

# Document Classification using Logistic regression

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,Y_train,Y_test = train_test_split(x,Y,random_state = 1, test_size = 0.5 ,shuffle = False)

import pickle
from sklearn.linear_model import LogisticRegressionCV

#Model
clf = LogisticRegressionCV(cv=5,
                          scoring = 'accuracy',
                          random_state = 0,
                          n_jobs = -3,
                          verbose = 3,
                          max_iter = 300).fit(x_train,Y_train)

#Saving the model
saved_model = open("saved_model.sav",'wb')

#using 
pickel.dump(clf,saved_model)

[Parallel(n_jobs=-3)]: Using backend LokyBackend with 2 concurrent workers.


# Model Evaluation

In [ ]:
filename = 'saved_model.sav'

saved_clf = pickle.load(open(filename,'rb'))

#test the saved model on test data
saved_clf.score(x_test,Y_test)